apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.appName }}-{{ .Release.Namespace }}.{{ .Values.domainName }}
  gateways:
  -  istio-system/public-gateway
  http:
  - match:
    - uri:
       prefix: /
    route:
    - destination:
        host: {{ .Values.appName }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
        allowOrigins:
          - exact: '*'
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowHeaders:
          - "*"
        exposeHeaders:
          - "*"
        allowCredentials: true

